language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

cache: vendor
sudo: false

script:
  - ./bin/sabre-cs-fixer fix --diff --dry-run .

before_script: composer install --dev
